"""empty message

Revision ID: 45272cd1d985
Revises: aa880472dd75
Create Date: 2018-09-20 19:50:23.935730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45272cd1d985'
down_revision = 'aa880472dd75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nick_name', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('head_image', sa.String(length=255), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_book_add_time'), 'guest_book', ['add_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guest_book_add_time'), table_name='guest_book')
    op.drop_table('guest_book')
    # ### end Alembic commands ###
