"""empty message

Revision ID: 8020d161821e
Revises: 2c3730171989
Create Date: 2018-09-19 23:09:53.599413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8020d161821e'
down_revision = '2c3730171989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'summary')
    # ### end Alembic commands ###
