"""empty message

Revision ID: 8287478757dc
Revises: cca6483c4471
Create Date: 2018-09-16 17:35:04.091744

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8287478757dc'
down_revision = 'cca6483c4471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('content', sa.Text(), nullable=True))
    op.drop_column('article', 'contitle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('contitle', mysql.TEXT(), nullable=True))
    op.drop_column('article', 'content')
    # ### end Alembic commands ###
