"""empty message

Revision ID: a79c25504c80
Revises: 6624f08e9a63
Create Date: 2018-09-18 18:20:14.351627

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a79c25504c80'
down_revision = '6624f08e9a63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('nick_name', sa.String(length=30), nullable=True))
    op.drop_column('comment', 'nike_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('nike_name', mysql.VARCHAR(length=30), nullable=True))
    op.drop_column('comment', 'nick_name')
    # ### end Alembic commands ###
